-- MySQL Script generated by MySQL Workbench
-- 06/30/16 02:47:48
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Time`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Time` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Time` (
  `nomeTime` VARCHAR(50) NOT NULL,
  `nomeArena` VARCHAR(45) NULL,
  `mascote` VARCHAR(45) NULL,
  `qtdTitulos` INT(11) NULL,
  `qtdVitorias` INT(11) NULL,
  `qtdDerrotas` INT(11) NULL,
  `qtdPontos` INT(11) NULL,
  `qtdEmpates` INT(11) NULL,
  `nomeTreinador` VARCHAR(45) NULL,
  PRIMARY KEY (`nomeTime`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`Jogador`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Jogador` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Jogador` (
  `nomeJogador` VARCHAR(45) NOT NULL,
  `apelido` VARCHAR(45) NULL,
  `posicao` VARCHAR(45) NULL,
  `qtdGolsCarreira` INT(11) NULL,
  `qtdCardAmarelo` INT(11) NULL,
  `qtdCardVermelho` INT(11) NULL,
  `idade` INT(11) NULL,
  PRIMARY KEY (`nomeJogador`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`Partida`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Partida` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Partida` (
  `id_Partida` INT NOT NULL,
  `empate` TINYINT(1) NULL,
  `data` DATETIME NULL,
  `placar` VARCHAR(45) NULL,
  `nomeArena` VARCHAR(45) NULL,
  PRIMARY KEY (`id_Partida`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`Campeonato`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Campeonato` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Campeonato` (
  `nome` VARCHAR(45) NOT NULL,
  `tabelaPontuacao` VARCHAR(45) NULL,
  `Partida_id_Partida` INT NOT NULL,
  `Partida_Time_nomeTime` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`nome`, `Partida_id_Partida`, `Partida_Time_nomeTime`),
  INDEX `fk_Campeonato_Partida1_idx` (`Partida_id_Partida` ASC, `Partida_Time_nomeTime` ASC),
  CONSTRAINT `fk_Campeonato_Partida1`
    FOREIGN KEY (`Partida_id_Partida`)
    REFERENCES `mydb`.`Partida` (`id_Partida`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`Titulo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Titulo` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Titulo` (
  `nivel` VARCHAR(45) NULL,
  `Campeonato_nome` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Campeonato_nome`),
  CONSTRAINT `fk_Titulo_Campeonato`
    FOREIGN KEY (`Campeonato_nome`)
    REFERENCES `mydb`.`Campeonato` (`nome`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Time_has_Jogador`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Time_has_Jogador` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Time_has_Jogador` (
  `Time_nomeTime` VARCHAR(50) NOT NULL,
  `Jogador_nomeJogador` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Time_nomeTime`, `Jogador_nomeJogador`),
  INDEX `fk_Time_has_Jogador_Jogador1_idx` (`Jogador_nomeJogador` ASC),
  INDEX `fk_Time_has_Jogador_Time1_idx` (`Time_nomeTime` ASC),
  CONSTRAINT `fk_Time_has_Jogador_Time1`
    FOREIGN KEY (`Time_nomeTime`)
    REFERENCES `mydb`.`Time` (`nomeTime`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Time_has_Jogador_Jogador1`
    FOREIGN KEY (`Jogador_nomeJogador`)
    REFERENCES `mydb`.`Jogador` (`nomeJogador`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`Partida_has_Time`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Partida_has_Time` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Partida_has_Time` (
  `Partida_id_Partida` INT NOT NULL,
  `Time_nomeTime_Vencedor` VARCHAR(50) NULL,
  `Time_nomeTime_Perdedor` VARCHAR(45) NULL,
  PRIMARY KEY (`Partida_id_Partida`),
  INDEX `fk_Partida_has_Time_Time1_idx` (`Time_nomeTime_Vencedor` ASC),
  INDEX `fk_Partida_has_Time_Partida1_idx` (`Partida_id_Partida` ASC),
  CONSTRAINT `fk_Partida_has_Time_Partida1`
    FOREIGN KEY (`Partida_id_Partida`)
    REFERENCES `mydb`.`Partida` (`id_Partida`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Partida_has_Time_Time1`
    FOREIGN KEY (`Time_nomeTime_Vencedor`)
    REFERENCES `mydb`.`Time` (`nomeTime`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
